export const ITEM_ACTION_TYPES = {
  REQUEST_GET_ITEM_BY_ID: "REQUEST_GET_ITEM_BY_ID",
  REQUEST_ADD_ITEM: "REQUEST_ADD_ITEM",
  REQUEST_UPDATE_ITEM: "REQUEST_UPDATE_ITEM",
  REQUEST_DELETE_ITEM: "REQUEST_DELETE_ITEM",
  DATA_GET_ITEM_BY_ID: "DATA_GET_ITEM_BY_ID",
  DATA_ADD_ITEM: "DATA_ADD_ITEM",
  DATA_UPDATE_ITEM: "DATA_UPDATE_ITEM",
  DATA_DELETE_ITEM: "DATA_DELETE_ITEM",
  COMMIT_GET_ITEM_BY_ID: "COMMIT_GET_ITEM_BY_ID",
  COMMIT_ADD_ITEM: "COMMIT_ADD_ITEM",
  COMMIT_UPDATE_ITEM: "COMMIT_UPDATE_ITEM",
  COMMIT_DELETE_ITEM: "COMMIT_DELETE_ITEM",
};
