export const ITEMS_ACTION_TYPES = {
  REQUEST_GET_ALL_ITEMS: "REQUEST_GET_ALL_ITEMS",
  REQUEST_ADD_ITEMS: "REQUEST_ADD_ITEMS",
  REQUEST_UPDATE_ITEMS: "REQUEST_UPDATE_ITEMS",
  REQUEST_DELETE_ITEMS: "REQUEST_DELETE_ITEMS",
  DATA_GET_ALL_ITEMS: "DATA_GET_ALL_ITEMS",
  DATA_ADD_ITEMS: "DATA_ADD_ITEMS",
  DATA_UPDATE_ITEMS: "DATA_UPDATE_ITEMS",
  DATA_DELETE_ITEMS: "DATA_DELETE_ITEMS",
  COMMIT_GET_ALL_ITEMS: "COMMIT_GET_ALL_ITEMS",
  COMMIT_ADD_ITEMS: "COMMIT_ADD_ITEMS",
  COMMIT_UPDATE_ITEMS: "COMMIT_UPDATE_ITEMS",
  COMMIT_DELETE_ITEMS: "COMMIT_DELETE_ITEMS",
};
